name: mert
description: This package helps you about request, decode response and creating sdk.
version: 0.0.2
homepage: https://github.com/imertgul/mert

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies: { test: ^1.21.4 }
# dev_dependencies:
